## tensorboardX
## sk-video
## pip install transforms3d
## pip install einops
## pip install meshcat
## pip install multipledispatch

name: agent-arena-v0
channels:
  - conda-forge
  - defaults
  - robostack-staging
  - robostack-humble 

dependencies:
  - pip
  - python
  - ros-humble-desktop
  #- python=3.7.7
  - pip:
    - ruamel.yaml
    - dotmap
    - gym #==0.23.1
    - h5py
    - tqdm
    #- opencv-python #==4.5.5.64
    - imutils #==0.5.4
    - matplotlib
    - moviepy
    - scikit-image
    - tensorboard
    - termcolor #==2.3.0
    - kornia #==0.6.12
    - pandas
    - charset-normalizer
    - pyquaternion
    - shapely
    - scikit-learn
    - pyswarm

    # Deformable Raven
    - transformations #==2020.1.1
    - pybullet #==3.0.4
    - circle-fit

    # DM Control
    - dm_control==1.0.13
    #- pytorch-lightning==1.9.5
    - tensorboardX
    - psutil
    - transforms3d
    - einops #==0.3.2
    - meshcat #==0.3.2
    - multipledispatch #==1.0.0

    - sk-video
    

    ## install realsense
    # pip install diffusers 0.21.4
    # pip install zarr 2.12.0