[project]
name = "agent-arena-v0"
version = "0.1.0"
description = "Bimanual manipulation research environment."
requires-python = ">=3.10"

authors = [
    { name = "Halid A. Kadi", email = "halidkadi.robot@gmail.com" }
]

readme = "README.md"

dependencies = [
    # Core scientific and ML stack
    "numpy<2.0",  # ensure compatibility with pybullet and other compiled deps
    "pybind11>=2.12.0",
    "ruamel.yaml==0.17.40",
    "seaborn==0.13.2",
    "dotmap==1.3.30",
    "gym==0.26.2",
    "h5py==3.11.0",
    "tqdm==4.66.5",
    "opencv-python==4.10.0.84",
    "imutils==0.5.4",
    "matplotlib==3.9.2",
    "moviepy==1.0.3",
    "scikit-image==0.24.0",
    "tensorboard==2.17.0",
    "termcolor==2.5.0",
    "kornia==0.7.2",
    "pandas==2.2.3",
    "charset-normalizer==3.4.0",
    "pyquaternion==0.9.9",
    "shapely==2.0.6",
    "scikit-learn==1.5.2",
    "pyswarm==0.6",
    "wandb==0.17.8",
    "transformations==2020.1.1",
    "pybullet==3.2.6",
    "circle-fit",
    "dm_control==1.0.21",
    "pytorch-lightning==2.4.0",
    "tensorboardX==2.6.2.2",
    "psutil==6.0.0",
    "transforms3d==0.4.2",
    "einops==0.8.0",
    "meshcat==0.3.2",
    "multipledispatch==1.0.0",
    "sk-video==1.1.10",
    "zarr==2.18.0",
    "open3d==0.18.0",
    "ray==2.38.0",
    "pygame==2.6.1",
    "pymunk==6.8.1",
    "gdown==5.2.0",
    "scipy>=1.10.0",
    "ur-rtde",
    "pyrealsense2",
    "omegaconf==2.3.0",  # needed for configuration management
    "hydra-core==1.3.2",  # NEW: required for hydra_train.py
    "robosuite==1.4.1",
    "gymnasium==0.29.1",
    "openai==2.15.0"
]

[project.optional-dependencies]
torch = [
    "torch==2.4.1",
    "torchvision==0.19.1",
    "torchaudio==2.4.1",
    "diffusers==0.36.0",
    "transformers==5.0.0"
    "accelerate==1.12.0"

]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# TODO: add AGENT_ARENA_PATH