n_rotations: 1
in_shape: [128, 128, 3]
crop_size: 32 # has to be even
pixel2world: False
train_mode: "from_policy"
num_train_demo_episodes: 3000
num_test_demo_episodes: 3
n_sample: 3000

total_update_steps: 80000
validation_interval: 10000
sl_update_steps: 80000
test_interval: 2000
batch_size: 10

action_dim: [1, 4]
encoder_version: 'resnet43'
pick_action_filter: "mask"
place_action_filter: "identity"
pick_and_place_policy: "probability_product"
input_obs: 'rgb'
# save_mask: True
# save_contour: True

logger_name: 'pick_and_place_fabric_single_task_logger'
save_heatmap: True
verbose: True

augmentation: False

transform:
  name: 'transporter_net_transformer'
  params:   
    device: "cuda:0"
    img_dim: [128, 128]
    rgb_norm_mode: ['remap']
    rgb_norm_param:
      remap_range: [-0.5, 0.5]
    rgb_noise_factor: 0.01
    swap_action: True

    depth_norm_mode: ['clip', 'min_max', 'remap'] 
    depth_norm_param:
      clip_range: [1.4, 1.5]
      min_max_range: [1.4, 1.5]
      remap_range: [-0.5, 0.5]
    depth_noise_factor: 0.01

    maskout: true
    
    random_rotation: true
    rotation_degree: 1
    vertical_flip: true

demo_policy:
  name: 'oracle-rect-fabric|action:pixel-pick-and-place(1),task:diagonal-cross-folding,strategy:expert'
  param:
    oracle: True


attention_optimiser:
  name: 'adam'
  params:
    lr: 1e-4


key_optimiser:
  name: 'adam'
  params:
    lr: 1e-4

  
query_optimiser:
  name: 'adam'
  params:
    lr: 1e-4