n_rotations: 36
in_shape: [320, 160, 6]
crop_size: 64 # has to be even
pixel2world: True
verbose: True
train_mode: "from_policy"
num_train_demo_episodes: 10
num_test_demo_episodes: 10
n_sample: 10
save_heatmap: True
save_mask: False
save_contour: False
batch_size: 1
action_mode: 'original'
validation_interval: 5000

encoder_version: 'resnet43'
total_update_steps: 40000
sl_update_steps: 40000
test_interval: 2000
input_obs: 'rgbd3'

pick_action_filter: 'identity'

# logger_name: 'standard_logger'

transform:
  name: 'transporter_net_transformer'
  params:   
    device: "cuda:0"
    rgb_norm_mode: ["remap", "normalise"]
    img_dim: [320, 160]
    rgb_norm_param:
      remap_range: [0, 1]
      mean: 0.18877631
      std: 0.07276466
    rgb_noise_factor: 0


    depth_norm_mode: ['normalise'] 
    depth_norm_param:
      mean: 0.00509261
      std: 0.00903967
    depth_noise_factor: 0


demo_policy:
  name: 'raven|task:block-insertion'
  param:
    oracle: True


attention_optimiser:
  name: 'adam'
  params:
    lr: 1e-4


key_optimiser:
  name: 'adam'
  params:
    lr: 1e-4

  
query_optimiser:
  name: 'adam'
  params:
    lr: 1e-4