n_rotations: 1
in_shape: [128, 128, 6]
crop_size: 32 # has to be even
pixel2world: False
train_mode: "from_policy"
num_train_demo_episodes: 10
num_test_demo_episodes: 3
n_sample: 10

total_update_steps: 20000
validation_interval: 5000
sl_update_steps: 20000
test_interval: 2000
batch_size: 10

action_dim: [1, 4]
encoder_version: 'resnet43'
pick_action_filter: "mask"
place_action_filter: "identity"
pick_and_place_policy: "probability_product"
num_pick_prob_prod: 200
input_obs: 'rgbd3'
save_mask: True
save_contour: True

logger_name: 'pick_and_place_fabric_single_task_logger'
save_heatmap: True
verbose: True

augmentation: False

transform:
  name: 'transporter_net_transformer'
  params:   
    device: "cuda:0"
    img_dim: [128, 128]
    rgb_norm_mode: ['remap']
    rgb_norm_param:
      remap_range: [0, 1]
    rgb_noise_factor: 0.02
    swap_action: True

    depth_norm_mode: ['clip', 'min_max', 'remap'] 
    depth_norm_param:
      clip_range: [0.55, 1.5]
      min_max_range: [0.55, 0.65]
      remap_range: [0, 1]
    depth_noise_factor: 0.01
    depth_flip: True

    
    random_rotation: true
    rotation_degree: 90
    vertical_flip: true

demo_policy:
  name: 'human-pixel-pick-and-place'
  param: 
    oracle: False


attention_optimiser:
  name: 'adam'
  params:
    lr: 1e-4


key_optimiser:
  name: 'adam'
  params:
    lr: 1e-4

  
query_optimiser:
  name: 'adam'
  params:
    lr: 1e-4