batch_size: 128
im_size: 128
init_termperature: 0.1
num_train_steps: 100
train_mode: 'online'
replay_buffer_capacity: 10000
obs_shape: [3, 128, 128]
action_shape: [4]
action_lower_bound: [-0.01, -0.01, -0.01, -1]
action_upper_bound: [0.01, 0.01, 0.01, 1]
num_eval_episodes: 2
log_interval: 10
save_video: true
save_model: true


lr_decay: null
critic_lr: 1e-4
alpha_lr: 1e-3
reward_sacle: 20


policy:
  name: 'self'